
remote_theme: williambenembarek/daydream-theme

lang: en
title: William Ben Embarek
email: william@embar.io
tagline: I am William, Hacker of Things, Lover of Keyboards, Sovereign of the Moon. 
description: >- # this means to ignore newlines until "baseurl:"
  William's Personal Site, you might learn something or then I just havn't posted anything yet...

cover: /assets/img/bg.jpg

author.name: William

baseurl: "" 
url: "https://embar.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: willbenem
github_username:  williambenembarek

# Build settings
plugins:
  - jekyll-feed
  - jekyll-remote-theme

